name: Create Release

on:
  workflow_call:
permissions:
  id-token: write                       # This is required for aws oidc connection
  pull-requests: write                  # This is required for gh bot to comment PR
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20'

      - name: Prepare Release
        run: |
          echo "REL=`date +%Y%m%d.%H%M%S`" >> $GITHUB_ENV
          echo "REL : ${REL}"

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: Rel:${REL}
          release_name: Release v${{ github.sha }}-${date '+%Y-%m-%d %H:%M:%S'}
          body: |
            Changes in this Release
              - Commit Message: ${{ github.event.head_commit.message }}
              - PR Comment: ${{ github.event.comment.body }}
          draft: false
          prerelease: false